# Generated by Django 2.2.15 on 2020-12-19 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='media/photos/')),
                ('photo_1', models.ImageField(blank=True, upload_to='media/photos/')),
                ('photo_2', models.ImageField(blank=True, upload_to='media/photos/')),
                ('photo_3', models.ImageField(blank=True, upload_to='media/photos/')),
                ('photo_4', models.ImageField(blank=True, upload_to='media/photos/')),
                ('photo_5', models.ImageField(blank=True, upload_to='media/photos/')),
                ('photo_6', models.ImageField(blank=True, upload_to='media/photos/')),
                ('in_stock', models.BooleanField(default=True)),
                ('sold', models.BooleanField(default=False)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
