# Generated by Django 2.2.15 on 2020-12-20 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo_main',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media/photos/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
